import { ThemeProvider } from "@/app/_components/theme-provider"
import "./globals.css"

import { RootFooter } from "@/app/_components/root-footer"
import { RootHeader } from "@/app/_components/root-header"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter } from "next/font/google"

const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        )}
      >
        <ThemeProvider>
          <RootHeader />
          {children}
          <RootFooter />
        </ThemeProvider>
      </body>
    </html>
  )
}
